agencias = [
  "RUA SANTA CLARA, 245", #
  "AVENIDA RUI BARBOSA, 2376", #
  "RUA RIACHUELO, 57",
  "AVENIDA ANDROMEDA, 1469", #
  "RUA SABARA, 30",
  "RUA EZEQUIEL ALVES GRACIANO, 140",
  "RUA QUINZE DE NOVEMBRO, 259",
  "AVENIDA DOUTOR NELSON D AVILA, 90",
  "RUA LOANDA, 895",
  "RUA GOIANIA, 15", #
]

pessoas_fisicas = [
  "RUA MATIAS PERES, 364",
  "RUA DA ALEGRIA, 39",
  "RUA CAPARAÓ, 370",
  "RUA ITUIUTABA, 50",
  "RUA PIMENTEIRAS, 322",
  "RUA CARVALHO DE ARAÚJO, 106 ",
  "RUA SAMUEL ANTÔNIO RODRIGUES, 197",
]

empresas = [
  "EMBRAER BRG. FARIA LIMA, 2170",
  "AKAER AV. CESARE MONSUETO GIULIO LATTES, 501",
  "DEDÉ CELLAV. ANDRÔMEDA, 654",
]

outros = [
  "UNESP AV. ENGENHEIRO FRANCISO JOSÉ LONGO, 777"
]